"""empty message

Revision ID: 729d1af0aeee
Revises: 7bae1f553b84
Create Date: 2025-06-03 14:54:23.536119

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '729d1af0aeee'
down_revision = '7bae1f553b84'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('personality',
    sa.Column('prsnlty_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('prompt', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('prsnlty_id')
    )
    with op.batch_alter_table('task_histories', schema=None) as batch_op:
        batch_op.alter_column('task1',
               existing_type=sa.VARCHAR(),
               type_=sa.Boolean(),
               existing_nullable=True)
        batch_op.alter_column('task2',
               existing_type=sa.VARCHAR(),
               type_=sa.Boolean(),
               existing_nullable=True)
        batch_op.alter_column('task3',
               existing_type=sa.VARCHAR(),
               type_=sa.Boolean(),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('task_histories', schema=None) as batch_op:
        batch_op.alter_column('task3',
               existing_type=sa.Boolean(),
               type_=sa.VARCHAR(),
               existing_nullable=True)
        batch_op.alter_column('task2',
               existing_type=sa.Boolean(),
               type_=sa.VARCHAR(),
               existing_nullable=True)
        batch_op.alter_column('task1',
               existing_type=sa.Boolean(),
               type_=sa.VARCHAR(),
               existing_nullable=True)

    op.drop_table('personality')
    # ### end Alembic commands ###
