"""empty message

Revision ID: ab541b3a0750
Revises: 
Create Date: 2025-06-20 10:57:37.174450

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ab541b3a0750'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('personality',
    sa.Column('prsnlty_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('prompt', sa.String(), nullable=True),
    sa.Column('rarity', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('prsnlty_id')
    )
    op.create_table('users',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('username', sa.String(), nullable=True),
    sa.Column('password_hash', sa.String(), nullable=True),
    sa.Column('point', sa.Integer(), nullable=True),
    sa.Column('task1_text', sa.String(), nullable=True),
    sa.Column('task2_text', sa.String(), nullable=True),
    sa.Column('task3_text', sa.String(), nullable=True),
    sa.Column('task1_judge', sa.Boolean(), nullable=True),
    sa.Column('task2_judge', sa.Boolean(), nullable=True),
    sa.Column('task3_judge', sa.Boolean(), nullable=True),
    sa.Column('task_date', sa.Date(), nullable=True),
    sa.Column('profile_image', sa.String(), nullable=True),
    sa.Column('gacha_point', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_username'), ['username'], unique=False)

    op.create_table('chat_histories',
    sa.Column('history_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.String(), nullable=True),
    sa.Column('user', sa.String(), nullable=True),
    sa.Column('model', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('history_id')
    )
    op.create_table('gacha_histories',
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('prsnlty_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['prsnlty_id'], ['personality.prsnlty_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'prsnlty_id')
    )
    op.create_table('task_histories',
    sa.Column('task_history_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.String(), nullable=True),
    sa.Column('task1', sa.Boolean(), nullable=True),
    sa.Column('task2', sa.Boolean(), nullable=True),
    sa.Column('task3', sa.Boolean(), nullable=True),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('task_history_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('task_histories')
    op.drop_table('gacha_histories')
    op.drop_table('chat_histories')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_username'))

    op.drop_table('users')
    op.drop_table('personality')
    # ### end Alembic commands ###
