"""empty message

Revision ID: e1f924d7df89
Revises: 74145594ea27
Create Date: 2025-06-06 15:01:53.289150

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e1f924d7df89'
down_revision = '74145594ea27'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('task', schema=None) as batch_op:
        batch_op.add_column(sa.Column('date', sa.DateTime(), nullable=True))
        batch_op.drop_column('date_judge')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('task', schema=None) as batch_op:
        batch_op.add_column(sa.Column('date_judge', sa.BOOLEAN(), nullable=True))
        batch_op.drop_column('date')

    # ### end Alembic commands ###
